packages:
  - packages/*
  - apps/*

catalog:
  zod: 4.3.5
  '@sentry/node': 10.22.0
  dotenv: 17.2.3
  react: '^19.2.1'
  react-dom: '^19.2.1'
  typescript: ^5.9.3
  '@types/react': '^19.2.7'
  '@types/react-dom': '^19.2.3'
  postcss: '^8.5.6'
  tailwindcss: '^4.1.17'
  qr-code-styling: '^1.9.2'
