name: 'Setup Continuous Integration'
description: 'Cache Dependencies'
runs:
  using: 'composite'
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22.14.0
        cache: 'pnpm'

    - name: Install Dependencies
      run: pnpm install
      shell: bash
