// Explicit named re-exports — do NOT switch this file to `export * from`.
// The CommonJS build target compiles `export *` to a runtime `__exportStar`
// loop that Node's ESM↔CJS interop cannot statically analyze, which would
// silently break `import { foo } from '@qrcodly/db'` from ESM consumers
// (e.g. apps/backend with `"type": "module"`).
export {
	qrCode,
	qrCodeRelations,
	type TQrCode,
	type TQrCodeWithRelations,
	qrCodeShare,
	qrCodeShareRelations,
	type TQrCodeShare,
	type TQrCodeShareWithQrCode,
	configTemplate,
	type TConfigTemplate,
	shortUrl,
	shortUrlRelations,
	type TShortUrl,
	type TShortUrlWithDomain,
	type TShortUrlWithDomainAndTags,
	SHORT_URL_SAFETY_STATUSES,
	type TShortUrlSafetyStatus,
	urlSafetyIncident,
	urlSafetyIncidentRelations,
	type TUrlSafetyIncident,
	URL_SAFETY_INCIDENT_SOURCES,
	URL_SAFETY_INCIDENT_ACTIONS,
	type TUrlSafetyIncidentSource,
	type TUrlSafetyIncidentAction,
	userSafetyStanding,
	userSafetyStandingRelations,
	type TUserSafetyStanding,
	shortUrlTag,
	shortUrlTagRelations,
	type TShortUrlTag,
	customDomain,
	customDomainRelations,
	type TCustomDomain,
	VERIFICATION_PHASES,
	SSL_STATUSES,
	OWNERSHIP_STATUSES,
	type TVerificationPhase,
	type TCloudflareSSLStatus,
	type TOwnershipStatus,
	userSubscription,
	type TUserSubscription,
	userAddonSubscription,
	type TUserAddonSubscription,
	ADDON_TYPES,
	type TAddonType,
	tag,
	tagRelations,
	type TTag,
	qrCodeTag,
	qrCodeTagRelations,
	type TQrCodeTag,
	analyticsIntegration,
	analyticsIntegrationRelations,
	type TAnalyticsIntegration,
	PROVIDER_TYPES,
	type TProviderType,
	userSurvey,
	type TUserSurvey,
} from './tables';
export { createTable } from './utils';
