name: Simple Task
description: A simple task/change
title: '[Chore]: '
labels: ['chore']
body:
  - type: markdown
    attributes:
      value: |
        ## Important Note
        Please fill out each section below, otherwise your issue will be closed. This information allows the maintainers to diagnose (and fix!) your problem as quickly as possible, which means you will receive a faster response.

  - type: textarea
    attributes:
      label: Activity Description
    validations:
      required: true
